name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Fixed version for Python 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pylint
        run: |
          pip install pylint

      - name: Run pylint
        run: |
          pylint **/*.py
        continue-on-error: true
          
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest
